name: Lint and Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.1

      - name: Install NPM dependencies
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Lint files
        run: yarn lint

      - name: Typecheck files
        run: yarn typescript

      - name: Run unit tests
        run: yarn test

      - name: Build package
        run: yarn prepare
